services:
    nextjs-app:
        image: nextjs-app
        container_name: nextjs-app
        build:
            context: .
            target: ${NODE_ENV}
            dockerfile: ./dockerfile
        ports:
            - '${APP_PORT}:${APP_PORT}'
        volumes:
            - ./next-app/src:/app/src
            - ./next-app/package.json:/app/package.json
            - ./next-app/public:/app/public
        env_file:
            - .env
        networks:
            - portfolio-network
    nestjs-server:
        image: nestjs-server
        container_name: nestjs-server
        build:
            context: .
            target: ${NODE_ENV}
            dockerfile: ./server.dockerfile
        ports:
            - '${SERVER_PORT}:${SERVER_PORT}'
        volumes:
            - ./nest-server/src:/server/src
            - ./nest-server/package.json:/server/package.json
        env_file:
            - .env
        networks:
            - portfolio-network    

networks:
    portfolio-network:
        driver: bridge
