services:
  nextjs-app:
    image: nextjs-app
    container_name: nextjs-app
    build:
      context: .
      target: ${NODE_ENV}
      dockerfile: ./dockerfile
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/package.json:/app/package.json
      - ./next-app/public:/app/public
      - ./.env:/app/.env
    env_file:
      - .env
    networks:
      - portfolio-network

  database:
    image: postgres:15
    container_name: database
    restart: always
    env_file:
      - .env
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-p", "${DATABASE_PORT}"]
    networks:
      - portfolio-network

  nestjs-server:
    image: nestjs-server
    container_name: nestjs-server
    build:
      context: .
      target: ${NODE_ENV}
      dockerfile: ./server.dockerfile
    ports:
      - "${SERVER_PORT}:7110"
    volumes:
      - ./nest-server/src:/server/src
      - ./nest-server/package.json:/server/package.json
      - .env:/server/.env
      - ./nest-server/prisma:/server/prisma
    env_file:
      - .env
    networks:
      - portfolio-network

volumes:
  postgres_data:

networks:
  portfolio-network:
    driver: bridge

