@hostname = http://localhost:7110/api
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXIiOnsiaWQiOjEsIm5hbWUiOiJhZG1pbiBhZG1pbiBhZG1pbiIsImdlbmRlciI6dHJ1ZSwiZW1haWwiOiJiYW9reW8wMDJAZ21haWwuY29tIiwicm9sZXMiOlsiYWRtaW4iXSwiY29tcGFueSI6InRlc3QgY29tcGFueSJ9LCJpYXQiOjE3NTY2NzIyMDksImV4cCI6MTc1NzI3NzAwOX0.xvssj6I9FJEVp5C_E0TIyb67vPILvwMyhYjDXuDDp04
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXIiOnsiaWQiOjEsIm5hbWUiOiJhZG1pbiBhZG1pbiBhZG1pbiIsImdlbmRlciI6dHJ1ZSwiZW1haWwiOiJiYW9reW8wMDJAZ21haWwuY29tIiwicm9sZXMiOlsiYWRtaW4iXSwiY29tcGFueSI6InRlc3QgY29tcGFueSJ9LCJpYXQiOjE3NTY2NzIyMDksImV4cCI6MTc1NjY3MjUwOX0.onS03VvBwg4J-Yf4L2QLSICpROnCIlV63nxVCD8e7Wo


###

GET {{hostname}} HTTP/1.1

### New Authorization Comment ###

POST {{hostname}}/comment/auth HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content": "Hello World"
}

### Register a new account

POST {{hostname}}/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "baohoang",
  "gender": true,
  "email": "hqbao202@gmail.com",
  "username": "admin",
  "password": "admin"
}

### Login to get access_token

POST {{hostname}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Refresh access token

POST {{hostname}}/auth/refresh HTTP/1.1
Cookie: refresh_token={{refreshToken}}

### Toggle Admin

PATCH {{hostname}}/auth/admin/1 HTTP/1.1



### New Comment

POST {{hostname}}/comment HTTP/1.1
Content-Type: application/json

{
  "username": "baohoang",
  "company": "Concentrix",
  "content": "This guy is super productive and have highly technical skill"
}

### Get Comments

GET {{hostname}}/comment HTTP/1.1

### Get feature project in homepage

GET {{hostname}}/project/feature HTTP/1.1



### OCS APP ###

POST {{hostname}}/project HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "CloudOCS App",
  "title": "CloudOCS - Omnichannel Cloud Sales",
  "feature": true,
  "projectType": "Mobile",
  "framework": ["Flutter", "PHP", "Firebase", "SocketIO", "ExpressJS"],
  "startAt": "2023-06-01",
  "endAt": "2023-08-01"
}

###

PATCH {{hostname}}/project/3 HTTP/1.1

{
  "feature": true
}

###

GET {{hostname}}/project?page=1
  &projectName=hello HTTP/1.1

###

POST {{hostname}}/language HTTP/1.1
Content-Type: application/json

{
  "displayStrings": [
    "C/C++",
    "Python",
    "Html/CSS",
    "Javascript",
    "Typescript",
    "PHP",
    "Dart",
    "Lua",
    "Shellscript",
    "Java",
    "C#",
    "Docker",
    "Prisma",
    "Google Services",
    "Facebook Services",
    "Zalo Services",
    "Redis Services"
  ]
}

###

GET {{hostname}}/language HTTP/1.1

###

DELETE {{hostname}}/language/17 HTTP/1.1

###

GET {{hostname}}/framework HTTP/1.1

###

POST {{hostname}}/framework HTTP/1.1
Content-Type: application/json

{
  "frameworks": [
    {
      "name": "Zalo Mini App - React",
      "languages": "Typescript"
    },
    {
      "name": "FacebookAPI",
      "languages": "Facebook Services"
    },
    {
      "name": "ZaloAPI",
      "languages": "Zalo Services"
    },
    {
      "name": "Smarty",
      "languages": "Html/CSS"
    },
    {
      "name": "jQuery",
      "languages": "Javascript"
    },
    {
      "name": "RabitMQ",
      "languages": "Redis Services"
    },
    {
      "name": "Unity",
      "languages": "C#"
    },
    {
      "name": "Flutter",
      "languages": "Dart"
    }
  ]
}

###

GET {{hostname}}/project-type HTTP/1.1

###

POST {{hostname}}/project-type HTTP/1.1
Content-Type: application/json

{
  "name": ["Mobile", "Web", "System", "Admin", "Default", "Game"]
}

### User section

POST {{hostname}}/comment/user-check HTTP/1.1
Content-Type: application/json
