name: Deploy Project
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy server and app into host
    if: ${{ always() }}
    runs-on: self-hosted
    steps:
      - name: Pull new code from server
        working-directory: /home/baohoang/Project/porfolio-project
        run: git fetch && git pull
      - name: Deploy using SSH
        working-directory: /home/baohoang/Project/porfolio-project
        run: docker compose down --rmi all && docker compose up -d
      - name: Update database
        working-directory: /home/baohoang/Project/porfolio-project/nest-server
        run: npm run docker:prisma:migrate
