name: Deploy Project
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy server and app into host
    if: ${{ always() }}
    runs-on: self-hosted
    steps:
      - name: Fetch latest code
        working-directory: /home/baohoang/Project/porfolio-project
        run: |
          git fetch origin main
          git reset --hard origin/main
      - name: Build images and start new images in docker-compose
        working-directory: /home/baohoang/Project/porfolio-project
        run: docker compose up -d --build
      - name: Migrate database
        working-directory: /home/baohoang/Project/porfolio-project/nest-server
        run: npm run docker:prisma:migrate
      - name: Clean up old images (optional)
        run: docker image prune -f
