name: Test Project
on:
  pull_request:
    branches:
      - master
jobs:
  deploy-server:
    name: Build Nest Server
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - name: Install package nest-server
        working-directory: ./nest-server
        run: npm install
      - name: Update prisma
        working-directory: ./nest-server
        run: npx prisma generate
      - name: Build nest-server
        working-directory: ./nest-server
        run: npm run build
  deploy-app:
    name: Build Next App
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - name: Install package react-app
        working-directory: ./next-app
        run: npm install
      - name: Build react-app
        working-directory: ./next-app
        run: npm run build
