name: Test Project
on:
  pull_request:
    branches:
      - master
jobs:
  test-build-server:
    name: Build Nest Server
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - name: Install package nest-server
        working-directory: ./nest-server
        run: npm install
      - name: Update prisma
        working-directory: ./nest-server
        run: npx prisma generate
      - name: Build nest-server
        working-directory: ./nest-server
        run: npm run build
  test-build-app:
    name: Build Next App
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - name: Install package react-app
        working-directory: ./next-app
        run: npm install
      - name: Build next-app
        working-directory: ./next-app
        run: npm run build
  auto-merge-into-master:
    name: Auto merge into master branch
    needs:
      - test-build-server
      - test-build-app
    if: github.base_ref == 'master' && github.head_ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install GitHub CLI
        run: sudo apt-get install gh -y
      - name: Auto merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin
